# Generated by Django 5.0.7 on 2024-07-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_contact_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='company',
        ),
        migrations.RemoveField(
            model_name='ourplans',
            name='company',
        ),
        migrations.RemoveField(
            model_name='ourservis',
            name='company',
        ),
        migrations.RemoveField(
            model_name='ourteem',
            name='company',
        ),
    ]
