# Generated by Django 5.0.7 on 2024-07-13 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_aboutus_company_remove_ourplans_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourplans',
            name='image',
        ),
    ]
